version: 2.1

jobs:
  build_and_push_image:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - run:
            name: Docker login
            command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - checkout
      - run: docker build -t yusukeito/grpcwebproxy:${CIRCLE_TAG} . && docker push yusukeito/grpcwebproxy:${CIRCLE_TAG}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image:
          context:
            - dockerhub
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
